/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/jobs/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentListItem"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAgentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentDetail"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAgentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentDetail"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KnowledgeItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{key}/work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    runs?: number | string;
                };
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentRunWork"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    provider?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeModelInfo"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    refresh?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderStatus"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeLoginStarted"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider}/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeAuthStatus"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    refresh?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeProviderLimits"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    runs?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UsageItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowListItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowDetail"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkflowModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowDetail"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scene/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scene/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number | string;
                    project?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Run"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RunRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunsOverview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    agent?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Turn"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Run"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectCard"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectCard"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectModel"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectCard"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{key}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number | string;
                };
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Run"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgentDetail: {
            key: string;
            name: string;
            summary: string;
            officeRoles: string[];
            provider: null | components["schemas"]["Provider"];
            model: null | string;
            effort: null | string;
            includes: string[];
            canAsk: null | string;
            prompt: string;
            composedPrompt: string;
        };
        AgentListItem: {
            key: string;
            name: string;
            summary: string;
            officeRoles: string[];
            provider: null | components["schemas"]["Provider"];
            model: null | string;
            effort: null | string;
            includes: string[];
            canAsk: null | string;
        };
        AgentRunWork: {
            run: components["schemas"]["Run"];
            turns: components["schemas"]["Turn"][];
            messages: components["schemas"]["Message"][];
            phases: components["schemas"]["Phase"][];
        };
        CreateAgentRequest: {
            key: string;
            name: string;
            summary: string;
            officeRoles: string[];
            provider: null | string;
            model: null | string;
            includes: string[];
            canAsk: null | string;
            prompt: string;
            effort?: null | string;
        };
        CreateProjectRequest: {
            key: string;
            title: string;
            description: null | string;
            workflow: null | string;
            targetDir: null | string;
        };
        /** @enum {unknown} */
        Destination: "local" | "anthropic" | "nvidia";
        InboxItem: {
            runId: string;
            label: string;
            status: components["schemas"]["RunStatus"];
            kind: components["schemas"]["InboxKind"];
            /** Format: date-time */
            ts: string;
            title: string;
            detail: null | string;
            task: null | string;
        };
        /** @enum {unknown} */
        InboxKind: "approval" | "decision" | "question";
        KnowledgeItem: {
            key: string;
            title: string;
            body: string;
        };
        LoginRequest: {
            mode: null | string;
            email: null | string;
        };
        Message: {
            /** Format: date-time */
            ts: string;
            kind: components["schemas"]["MessageKind"];
            from: string;
            to: string;
            body: string;
            task?: null | string;
            stage?: null | string;
            ref?: null | string;
            /** @default  */
            subject: string;
        };
        /** @enum {unknown} */
        MessageKind: "ask" | "answer" | "handoff" | "note";
        Phase: {
            /** Format: date-time */
            ts: string;
            task: string;
            stage: string;
            stageTitle: string;
            kind: string;
            agent: string;
            /** Format: int32 */
            round: number | string;
            status: components["schemas"]["PhaseStatus"];
            /** Format: double */
            durationS?: null | number | string;
            detail?: null | string;
        };
        /** @enum {unknown} */
        PhaseStatus: "started" | "done" | "rejected" | "failed" | "skipped";
        ProjectCard: {
            key: string;
            title: string;
            description: string;
            workflow: string;
            targetDir: string;
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: int32 */
            runs: number | string;
            /** Format: int32 */
            running: number | string;
            /** Format: int32 */
            awaitingApproval: number | string;
            /** Format: int32 */
            paused: number | string;
            /** Format: int32 */
            failed: number | string;
            /** Format: int32 */
            completed: number | string;
            /** Format: double */
            totalCostUsd: number | string;
            /** Format: date-time */
            lastActivityAt: null | string;
        };
        ProjectModel: {
            title: string;
            description: null | string;
            workflow: null | string;
            targetDir: null | string;
        };
        /** @enum {unknown} */
        Provider: "anthropic" | "nvidia" | "ollama" | null;
        ProviderStatus: {
            provider: components["schemas"]["Provider"];
            loggedIn: boolean;
            account: null | string;
            detail: string;
            models: components["schemas"]["RuntimeModelInfo"][];
        };
        ReviseRequest: {
            note: string;
        };
        Run: {
            id: string;
            label: string;
            brief: string;
            sensitivity: components["schemas"]["Sensitivity"];
            /** Format: date-time */
            startedAt: string;
            status: components["schemas"]["RunStatus"];
            /** Format: date-time */
            finishedAt?: null | string;
            /**
             * Format: double
             * @default 0
             */
            totalCostUsd: number | string;
            /** @default default */
            workflow: string;
            detail?: null | string;
            /** Format: double */
            maxCostUsd?: null | number | string;
            /**
             * Format: int32
             * @default 0
             */
            retries: number | string;
            /** @default  */
            project: string;
            /** @default local */
            ownerId: string;
            isCancellable?: boolean;
            isRetryable?: boolean;
        };
        RunDetail: {
            id: string;
            label: string;
            brief: string;
            sensitivity: components["schemas"]["Sensitivity"];
            workflow: string;
            status: components["schemas"]["RunStatus"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            finishedAt: null | string;
            /** Format: double */
            totalCostUsd: number | string;
            detail: null | string;
            /** Format: double */
            maxCostUsd: null | number | string;
            /** Format: int32 */
            retries: number | string;
            project: string;
            ownerId: string;
            workflowDef: null | components["schemas"]["WorkflowDetail"];
            spec: null | components["schemas"]["Spec"];
            order: string[];
            tasks: components["schemas"]["TaskPhases"][];
            messages: components["schemas"]["Message"][];
        };
        RunRequest: {
            brief: string;
            workflow?: null | string;
            sensitivity?: null | components["schemas"]["Sensitivity"];
            label?: null | string;
            /** Format: double */
            maxCostUsd?: null | number | string;
            project?: null | string;
        };
        /** @enum {unknown} */
        RunStatus: "running" | "completed" | "failed" | "interrupted" | "budgetExceeded" | "policyRejected" | "awaitingApproval" | "paused" | "cancelled";
        RunTask: {
            id: string;
            title: string;
            description: string;
            files: string[];
            acceptance: string[];
            dependsOn: string[];
        };
        RunsOverview: {
            /** Format: int32 */
            total: number | string;
            /** Format: int32 */
            running: number | string;
            /** Format: int32 */
            awaitingApproval: number | string;
            /** Format: int32 */
            paused: number | string;
            /** Format: int32 */
            failed: number | string;
            /** Format: int32 */
            completed: number | string;
            /** Format: int32 */
            cancelled: number | string;
            inbox: components["schemas"]["InboxItem"][];
        };
        RuntimeAuthStatus: {
            provider: components["schemas"]["Provider"];
            loggedIn: boolean;
            account: null | string;
            detail: string;
        };
        RuntimeLoginStarted: {
            provider: components["schemas"]["Provider"];
            started: boolean;
            detail: string;
        };
        RuntimeModelInfo: {
            provider: components["schemas"]["Provider"];
            model: string;
            reachable: boolean;
            detail: string;
        };
        RuntimeProviderLimits: {
            provider: components["schemas"]["Provider"];
            available: boolean;
            detail: string;
            subscription: null | string;
            /** Format: date-time */
            fetchedAt: null | string;
            limits: components["schemas"]["RuntimeUsageLimit"][];
        };
        RuntimeUsageLimit: {
            kind: string;
            group: null | string;
            /** Format: double */
            percent: number | string;
            severity: null | string;
            /** Format: date-time */
            resetsAt: null | string;
            scope: null | string;
            isActive: boolean;
        };
        /** @enum {unknown} */
        Sensitivity: "local" | "anthropic" | "open";
        Spec: {
            summary: string;
            architecture: string;
            rules: string[];
            tasks: components["schemas"]["RunTask"][];
        };
        /** @enum {unknown} */
        StageKind: "analyze" | "design" | "implement" | "review" | "handoff";
        StageModel: {
            id: string;
            title: string;
            kind: components["schemas"]["StageKind"];
            role: string;
            officeRole: string;
            description: string;
        };
        TaskPhases: {
            id: string;
            phases: components["schemas"]["Phase"][];
        };
        Turn: {
            /** Format: date-time */
            ts: string;
            agent: string;
            stage: null | string;
            task: null | string;
            /** Format: int32 */
            round: null | number | string;
            provider: string;
            model: string;
            destination: components["schemas"]["Destination"];
            /** Format: double */
            durationS: number | string;
            /** Format: int32 */
            promptChars: number | string;
            /** Format: int32 */
            outputChars: number | string;
            /** Format: double */
            costUsd?: null | number | string;
            prompt?: null | string;
            output?: null | string;
            /** Format: int32 */
            inputTokens?: null | number | string;
            /** Format: int32 */
            outputTokens?: null | number | string;
        };
        UpdateAgentRequest: {
            name: string;
            summary: string;
            officeRoles: string[];
            provider: null | string;
            model: null | string;
            includes: string[];
            canAsk: null | string;
            prompt: string;
            effort?: null | string;
        };
        UsageItem: {
            provider: string;
            model: string;
            /** Format: int32 */
            turns: number | string;
            /** Format: int32 */
            runs: number | string;
            /** Format: int64 */
            inputTokens: number | string;
            /** Format: int64 */
            outputTokens: number | string;
            /** Format: double */
            costUsd: number | string;
            /** Format: date-time */
            lastAt: null | string;
        };
        WorkflowDetail: {
            key: string;
            title: string;
            /** Format: int32 */
            maxReviewRounds: number | string;
            handoffRole: null | string;
            stages: components["schemas"]["StageModel"][];
        };
        WorkflowListItem: {
            key: string;
            title: string;
            isDefault: boolean;
            /** Format: int32 */
            stageCount: number | string;
            roles: string[];
        };
        WorkflowModel: {
            title: string;
            /** Format: int32 */
            maxReviewRounds: number | string;
            handoffRole: null | string;
            stages: components["schemas"]["StageModel"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
